version: '3.4'

services:

  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  coupondb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  identitydb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: