version: '3.4'

services:

  catalogdb:
    container_name: catalogdb
    restart: no
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"

  basketdb:
    container_name: basketdb
    restart: no
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=Discountdb
    restart: no
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: no
    ports:
        - "1433:1433"
  coupondb:
    container_name: coupondb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: no
    ports:
        - "1434:1433"

  identitydb:
    container_name: identitydb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: no
    ports:
        - "1435:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: no
    ports:
        - "5672:5672"
        - "15672:15672"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@burakcoskun.net
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: no
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: no
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

